
name: hugo-build

on:
  workflow_call:
    inputs:
      source:
        required: true
        type: string
      build:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      COMMAND:
        required: true

jobs:
  build:
    name: hugo build
    runs-on: ubuntu-latest
    steps:
      - uses: cc332030/hugo-asciidoctor-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ${{ github.actor }}
          EMAIL: ${{ github.actor }}@gmail.com
          COMMAND: ${{ secrets.COMMAND }}
        with:
          source: ${{ inputs.source }}
          build: ${{ inputs.build }}
      - id: artifact-name
        name: artifact-name
        run: |
          echo "artifact-name=${{ github.event.repository.name }}.${{ github.ref_name }}.${{ github.run_id }}" >> $GITHUB_OUTPUT
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.artifact-name }}
          path: |
            build
